version: "3.8"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - .db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    
  wordpress:
    depends_on:
      - db
    image: wordpress:${WOPRDPRESS_VER}
    volumes:
      - ./public:/var/www/html:rw
      # - ./public_html:/var/www/html:rw
    ports:
      - ${WOPRDPRESS_PORT}:80
    restart: always
    user: ${UUID}:${GID}
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
      WORDPRESS_DEBUG_LOG: ${WORDPRESS_DEBUG_LOG}
      WORDPRESS_DEBUG_DISPLAY: ${WORDPRESS_DEBUG_DISPLAY}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_DB_TABLE_PREFIX}
volumes:
  db_data: {}
  wordpress_data: {}